# Build Stage
FROM node:16-alpine AS builder
WORKDIR /app
COPY src/package*.json ./
RUN npm install --only=production

# Production Stage
FROM node:16-alpine AS production
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY src/package*.json ./
COPY src/server.js ./
COPY src/index.html ./

RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
USER nodejs
EXPOSE 3000
CMD ["npm", "start"]
