FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y nginx
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN apt-get clean
RUN rm /var/www/html/index.nginx-debian.html
COPY src/index.html /var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
